<title>{{PageTitle|default('#KTTT17')}}</title>
<link rel="shortcut icon" href="/static/img/favicon.ico" type="image/x-icon" />
<link rel="icon" href="/static/img/favicon.ico" type="image/ico" />
{% if IsDev %}
	<link rel="stylesheet" href="/static/css/devdata.css" />
	<div id="dev-data-banner-wrap" class="clearfix">
		<div class="dev-data-banner">
			<p class="dev-data-banner-text">Dev Data</p>
		</div>
	</div>
{% endif %}
