let os = require('os');
let router = require('express').Router();
// var _ = require('underscore');
let pm2 = require('pm2');

module.exports = () => {

	router.get('/', (req, res) => {
		pm2.list((err, procs) => {
			if (err)
				return res.status(500).send(err);

			let cpus = os.cpus();
			let items = [
				{ key: 'cpu', value: cpus[0].model },
				{ key: 'cores', value: cpus.length },
				{ key: 'cluster nodes', value: procs.length }
			];
			res.render('server/about', { items: items });
		});
	});

	router.get('/pm2', (req, res) => {

	});

	return router;
};

// [
// 	{
// 		"pid":11204,
// 		"name":"dkmerger",
// 		"pm2_env":{
// 			"exec_mode":"cluster_mode",
// 			"env":{
// 				"dkmerger":"{}",
// 				"PM2_HOME":"C:\\Users\\connor\\.pm2",
// 				"windir":"C:\\Windows",
// 				"VSSDK140Install":"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VSSDK\\",
// 				"VS140COMNTOOLS":"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\",
// 				"USERPROFILE":"C:\\Users\\connor",
// 				"USERNAME":"connor",
// 				"USERDOMAIN_ROAMINGPROFILE":"CJTKENNEDY",
// 				"USERDOMAIN":"CJTKENNEDY",
// 				"USERDNSDOMAIN":"CJTKENNEDY.COM",
// 				"TMP":"C:\\Users\\connor\\AppData\\Local\\Temp\\",
// 				"TERM":"msys",
// 				"TEMP":"C:\\Users\\connor\\AppData\\Local\\Temp\\",
// 				"SystemRoot":"C:\\Windows",
// 				"SystemDrive":"C:",
// 				"SSH_AUTH_SOCK":"/tmp/ssh-zWVv5FFUKvDv/agent.12184",
// 				"SSH_AGENT_PID":"12276",
// 				"SESSIONNAME":"Console",
// 				"REDISCLOUD_URL":"redis://rediscloud:J4mdu6a6dYShaddE@redis-18664.c8.us-east-1-3.ec2.cloud.redislabs.com:18664",
// 				"PUBLIC":"C:\\Users\\Public",
// 				"PSModulePath":"C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Users\\connor\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files (x86)\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
// 				"PSExecutionPolicyPreference":"Unrestricted",
// 				"ProgramW6432":"C:\\Program Files",
// 				"ProgramFiles(x86)":"C:\\Program Files (x86)",
// 				"ProgramFiles":"C:\\Program Files",
// 				"ProgramData":"C:\\ProgramData",
// 				"PROCESSOR_REVISION":"0200",
// 				"PROCESSOR_LEVEL":"21",
// 				"PROCESSOR_IDENTIFIER":"AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD",
// 				"PROCESSOR_ARCHITECTURE":"AMD64",
// 				"posh_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PoshGit_a2be688889e1b24632e83adccd9b2a44b91d655b\\profile.example.ps1",
// 				"PM2_PROGRAMMATIC":"true",
// 				"PM2_JSON_PROCESSING":"true",
// 				"PM2_INTERACTOR_PROCESSING":"true",
// 				"PLINK_PROTOCOL":"ssh",
// 				"PGSSLMODE":"require",
// 				"PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
// 				"Path":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\cmd;C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\usr\\bin;C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\usr\\share\\git-tfs;C:\\Users\\connor\\AppData\\Local\\Apps\\2.0\\X9Q91ADO.37Z\\Z0KKYXX8.73L\\gith..tion_317444273a93ac29_0003.0003_665ccbdbd3c2d8d4;C:\\Users\\connor\\AppData\\Local\\GitHub\\lfs-amd64_1.3.1;C:\\Python27\\;C:\\Python27\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git\\cmd;C:\\Windows\\system32\\config\\systemprofile\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Users\\connor\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\connor\\AppData\\Roaming\\npm;C:\\Program Files\\rclone;C:\\Program Files\\Heroku\\bin;C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v8.1A\\bin\\NETFX 4.5.1 Tools\\x64",
// 				"OS":"Windows_NT",
// 				"OneDrive":"C:\\Users\\connor\\OneDrive",
// 				"NUMBER_OF_PROCESSORS":"8",
// 				"NODE_ENV":"development",
// 				"MOZ_PLUGIN_PATH":"C:\\Program Files (x86)\\Foxit Software\\Foxit Reader\\plugins\\",
// 				"LOGONSERVER":"\\\\ADC",
// 				"LOCALAPPDATA":"C:\\Users\\connor\\AppData\\Local",
// 				"HOMEPATH":"\\Users\\connor",
// 				"HOMEDRIVE":"C:",
// 				"HOME":"C:\\Users\\connor",
// 				"git_install_root":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11",
// 				"github_shell":"true",
// 				"github_posh_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PoshGit_a2be688889e1b24632e83adccd9b2a44b91d655b",
// 				"github_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11",
// 				"EDITOR":"GitPad",
// 				"DATABASE_URL":"postgres://tzluogucwufjfr:4a65cb2ed4d7a1c8ca0df85f9ee5549aa33e50c176161e137e47fca2b3b7542d@ec2-54-235-92-236.compute-1.amazonaws.com:5432/d9m59b6dn4gol2",
// 				"ComSpec":"C:\\Windows\\system32\\cmd.exe",
// 				"COMPUTERNAME":"CONNORPC",
// 				"CommonProgramW6432":"C:\\Program Files\\Common Files",
// 				"CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files",
// 				"CommonProgramFiles":"C:\\Program Files\\Common Files",
// 				"asl.log":"Destination=file",
// 				"APPDATA":"C:\\Users\\connor\\AppData\\Roaming",
// 				"ALLUSERSPROFILE":"C:\\ProgramData"
// 			},
// 			"treekill":true,
// 			"autorestart":true,
// 			"automation":true,
// 			"pmx":true,
// 			"vizion":true,
// 			"instances":4,
// 			"max_memory_restart":536870912,
// 			"name":"dkmerger",
// 			"node_args":[
//
// 			],
// 			"pm_exec_path":"C:\\Users\\connor\\Documents\\GitHub\\wedding\\app.js",
// 			"pm_cwd":"C:\\Users\\connor\\Documents\\GitHub\\wedding",
// 			"exec_interpreter":"node",
// 			"pm_out_log_path":"C:\\Users\\connor\\.pm2\\logs\\dkmerger-out-0.log",
// 			"pm_err_log_path":"C:\\Users\\connor\\.pm2\\logs\\dkmerger-error-0.log",
// 			"pm_pid_path":"C:\\Users\\connor\\.pm2\\pids\\dkmerger-0.pid",
// 			"NODE_APP_INSTANCE":0,
// 			"vizion_running":false,
// 			"dkmerger":"{}",
// 			"PM2_HOME":"C:\\Users\\connor\\.pm2",
// 			"windir":"C:\\Windows",
// 			"VSSDK140Install":"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VSSDK\\",
// 			"VS140COMNTOOLS":"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\",
// 			"USERPROFILE":"C:\\Users\\connor",
// 			"USERNAME":"connor",
// 			"USERDOMAIN_ROAMINGPROFILE":"CJTKENNEDY",
// 			"USERDOMAIN":"CJTKENNEDY",
// 			"USERDNSDOMAIN":"CJTKENNEDY.COM",
// 			"TMP":"C:\\Users\\connor\\AppData\\Local\\Temp\\",
// 			"TERM":"msys",
// 			"TEMP":"C:\\Users\\connor\\AppData\\Local\\Temp\\",
// 			"SystemRoot":"C:\\Windows",
// 			"SystemDrive":"C:",
// 			"SSH_AUTH_SOCK":"/tmp/ssh-zWVv5FFUKvDv/agent.12184",
// 			"SSH_AGENT_PID":"12276",
// 			"SESSIONNAME":"Console",
// 			"REDISCLOUD_URL":"redis://rediscloud:J4mdu6a6dYShaddE@redis-18664.c8.us-east-1-3.ec2.cloud.redislabs.com:18664",
// 			"PUBLIC":"C:\\Users\\Public",
// 			"PSModulePath":"C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Users\\connor\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files (x86)\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
// 			"PSExecutionPolicyPreference":"Unrestricted",
// 			"ProgramW6432":"C:\\Program Files",
// 			"ProgramFiles(x86)":"C:\\Program Files (x86)",
// 			"ProgramFiles":"C:\\Program Files",
// 			"ProgramData":"C:\\ProgramData",
// 			"PROCESSOR_REVISION":"0200",
// 			"PROCESSOR_LEVEL":"21",
// 			"PROCESSOR_IDENTIFIER":"AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD",
// 			"PROCESSOR_ARCHITECTURE":"AMD64",
// 			"posh_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PoshGit_a2be688889e1b24632e83adccd9b2a44b91d655b\\profile.example.ps1",
// 			"PM2_PROGRAMMATIC":"true",
// 			"PM2_JSON_PROCESSING":"true",
// 			"PM2_INTERACTOR_PROCESSING":"true",
// 			"PLINK_PROTOCOL":"ssh",
// 			"PGSSLMODE":"require",
// 			"PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
// 			"Path":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\cmd;C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\usr\\bin;C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\usr\\share\\git-tfs;C:\\Users\\connor\\AppData\\Local\\Apps\\2.0\\X9Q91ADO.37Z\\Z0KKYXX8.73L\\gith..tion_317444273a93ac29_0003.0003_665ccbdbd3c2d8d4;C:\\Users\\connor\\AppData\\Local\\GitHub\\lfs-amd64_1.3.1;C:\\Python27\\;C:\\Python27\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git\\cmd;C:\\Windows\\system32\\config\\systemprofile\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Users\\connor\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\connor\\AppData\\Roaming\\npm;C:\\Program Files\\rclone;C:\\Program Files\\Heroku\\bin;C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v8.1A\\bin\\NETFX 4.5.1 Tools\\x64",
// 			"OS":"Windows_NT",
// 			"OneDrive":"C:\\Users\\connor\\OneDrive",
// 			"NUMBER_OF_PROCESSORS":"8",
// 			"NODE_ENV":"development",
// 			"MOZ_PLUGIN_PATH":"C:\\Program Files (x86)\\Foxit Software\\Foxit Reader\\plugins\\",
// 			"LOGONSERVER":"\\\\ADC",
// 			"LOCALAPPDATA":"C:\\Users\\connor\\AppData\\Local",
// 			"HOMEPATH":"\\Users\\connor",
// 			"HOMEDRIVE":"C:",
// 			"HOME":"C:\\Users\\connor",
// 			"git_install_root":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11",
// 			"github_shell":"true",
// 			"github_posh_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PoshGit_a2be688889e1b24632e83adccd9b2a44b91d655b",
// 			"github_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11",
// 			"EDITOR":"GitPad",
// 			"DATABASE_URL":"postgres://tzluogucwufjfr:4a65cb2ed4d7a1c8ca0df85f9ee5549aa33e50c176161e137e47fca2b3b7542d@ec2-54-235-92-236.compute-1.amazonaws.com:5432/d9m59b6dn4gol2",
// 			"ComSpec":"C:\\Windows\\system32\\cmd.exe",
// 			"COMPUTERNAME":"CONNORPC",
// 			"CommonProgramW6432":"C:\\Program Files\\Common Files",
// 			"CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files",
// 			"CommonProgramFiles":"C:\\Program Files\\Common Files",
// 			"asl.log":"Destination=file",
// 			"APPDATA":"C:\\Users\\connor\\AppData\\Roaming",
// 			"ALLUSERSPROFILE":"C:\\ProgramData",
// 			"status":"online",
// 			"pm_uptime":1483646656611,
// 			"axm_actions":[
//
// 			],
// 			"axm_monitor":{
// 				"Loop delay":{
// 					"alert":{
//
// 					},
// 					"agg_type":"avg",
// 					"value":"44.85ms"
// 				}
// 			},
// 			"axm_options":{
// 				"default_actions":true,
// 				"http":false,
// 				"http_latency":200,
// 				"http_code":500,
// 				"ignore_routes":[
//
// 				],
// 				"profiling":true,
// 				"errors":true,
// 				"alert_enabled":true,
// 				"custom_probes":true,
// 				"network":false,
// 				"ports":false,
// 				"module_conf":{
//
// 				},
// 				"module_name":"dkmerger",
// 				"module_version":"2.2.3",
// 				"pmx_version":"0.6.8",
// 				"error":true
// 			},
// 			"axm_dynamic":{
//
// 			},
// 			"created_at":1483646656611,
// 			"pm_id":0,
// 			"restart_time":0,
// 			"unstable_restarts":0,
// 			"_pm2_version":"2.2.3",
// 			"versioning":null,
// 			"node_version":"7.1.0"
// 		},
// 		"pm_id":0,
// 		"monit":{
// 			"memory":52772864,
// 			"cpu":270
// 		}
// 	},
// 	{
// 		"pid":10844,
// 		"name":"dkmerger",
// 		"pm2_env":{
// 			"exec_mode":"cluster_mode",
// 			"env":{
// 				"dkmerger":"{}",
// 				"PM2_HOME":"C:\\Users\\connor\\.pm2",
// 				"windir":"C:\\Windows",
// 				"VSSDK140Install":"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VSSDK\\",
// 				"VS140COMNTOOLS":"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\",
// 				"USERPROFILE":"C:\\Users\\connor",
// 				"USERNAME":"connor",
// 				"USERDOMAIN_ROAMINGPROFILE":"CJTKENNEDY",
// 				"USERDOMAIN":"CJTKENNEDY",
// 				"USERDNSDOMAIN":"CJTKENNEDY.COM",
// 				"TMP":"C:\\Users\\connor\\AppData\\Local\\Temp\\",
// 				"TERM":"msys",
// 				"TEMP":"C:\\Users\\connor\\AppData\\Local\\Temp\\",
// 				"SystemRoot":"C:\\Windows",
// 				"SystemDrive":"C:",
// 				"SSH_AUTH_SOCK":"/tmp/ssh-zWVv5FFUKvDv/agent.12184",
// 				"SSH_AGENT_PID":"12276",
// 				"SESSIONNAME":"Console",
// 				"REDISCLOUD_URL":"redis://rediscloud:J4mdu6a6dYShaddE@redis-18664.c8.us-east-1-3.ec2.cloud.redislabs.com:18664",
// 				"PUBLIC":"C:\\Users\\Public",
// 				"PSModulePath":"C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Users\\connor\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files (x86)\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
// 				"PSExecutionPolicyPreference":"Unrestricted",
// 				"ProgramW6432":"C:\\Program Files",
// 				"ProgramFiles(x86)":"C:\\Program Files (x86)",
// 				"ProgramFiles":"C:\\Program Files",
// 				"ProgramData":"C:\\ProgramData",
// 				"PROCESSOR_REVISION":"0200",
// 				"PROCESSOR_LEVEL":"21",
// 				"PROCESSOR_IDENTIFIER":"AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD",
// 				"PROCESSOR_ARCHITECTURE":"AMD64",
// 				"posh_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PoshGit_a2be688889e1b24632e83adccd9b2a44b91d655b\\profile.example.ps1",
// 				"PM2_PROGRAMMATIC":"true",
// 				"PM2_JSON_PROCESSING":"true",
// 				"PM2_INTERACTOR_PROCESSING":"true",
// 				"PLINK_PROTOCOL":"ssh",
// 				"PGSSLMODE":"require",
// 				"PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
// 				"Path":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\cmd;C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\usr\\bin;C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\usr\\share\\git-tfs;C:\\Users\\connor\\AppData\\Local\\Apps\\2.0\\X9Q91ADO.37Z\\Z0KKYXX8.73L\\gith..tion_317444273a93ac29_0003.0003_665ccbdbd3c2d8d4;C:\\Users\\connor\\AppData\\Local\\GitHub\\lfs-amd64_1.3.1;C:\\Python27\\;C:\\Python27\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git\\cmd;C:\\Windows\\system32\\config\\systemprofile\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Users\\connor\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\connor\\AppData\\Roaming\\npm;C:\\Program Files\\rclone;C:\\Program Files\\Heroku\\bin;C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v8.1A\\bin\\NETFX 4.5.1 Tools\\x64",
// 				"OS":"Windows_NT",
// 				"OneDrive":"C:\\Users\\connor\\OneDrive",
// 				"NUMBER_OF_PROCESSORS":"8",
// 				"NODE_ENV":"development",
// 				"MOZ_PLUGIN_PATH":"C:\\Program Files (x86)\\Foxit Software\\Foxit Reader\\plugins\\",
// 				"LOGONSERVER":"\\\\ADC",
// 				"LOCALAPPDATA":"C:\\Users\\connor\\AppData\\Local",
// 				"HOMEPATH":"\\Users\\connor",
// 				"HOMEDRIVE":"C:",
// 				"HOME":"C:\\Users\\connor",
// 				"git_install_root":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11",
// 				"github_shell":"true",
// 				"github_posh_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PoshGit_a2be688889e1b24632e83adccd9b2a44b91d655b",
// 				"github_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11",
// 				"EDITOR":"GitPad",
// 				"DATABASE_URL":"postgres://tzluogucwufjfr:4a65cb2ed4d7a1c8ca0df85f9ee5549aa33e50c176161e137e47fca2b3b7542d@ec2-54-235-92-236.compute-1.amazonaws.com:5432/d9m59b6dn4gol2",
// 				"ComSpec":"C:\\Windows\\system32\\cmd.exe",
// 				"COMPUTERNAME":"CONNORPC",
// 				"CommonProgramW6432":"C:\\Program Files\\Common Files",
// 				"CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files",
// 				"CommonProgramFiles":"C:\\Program Files\\Common Files",
// 				"asl.log":"Destination=file",
// 				"APPDATA":"C:\\Users\\connor\\AppData\\Roaming",
// 				"ALLUSERSPROFILE":"C:\\ProgramData"
// 			},
// 			"treekill":true,
// 			"autorestart":true,
// 			"automation":true,
// 			"pmx":true,
// 			"vizion":true,
// 			"instances":4,
// 			"max_memory_restart":536870912,
// 			"name":"dkmerger",
// 			"node_args":[
//
// 			],
// 			"pm_exec_path":"C:\\Users\\connor\\Documents\\GitHub\\wedding\\app.js",
// 			"pm_cwd":"C:\\Users\\connor\\Documents\\GitHub\\wedding",
// 			"exec_interpreter":"node",
// 			"pm_out_log_path":"C:\\Users\\connor\\.pm2\\logs\\dkmerger-out-1.log",
// 			"pm_err_log_path":"C:\\Users\\connor\\.pm2\\logs\\dkmerger-error-1.log",
// 			"pm_pid_path":"C:\\Users\\connor\\.pm2\\pids\\dkmerger-1.pid",
// 			"NODE_APP_INSTANCE":1,
// 			"vizion_running":false,
// 			"dkmerger":"{}",
// 			"PM2_HOME":"C:\\Users\\connor\\.pm2",
// 			"windir":"C:\\Windows",
// 			"VSSDK140Install":"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VSSDK\\",
// 			"VS140COMNTOOLS":"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\",
// 			"USERPROFILE":"C:\\Users\\connor",
// 			"USERNAME":"connor",
// 			"USERDOMAIN_ROAMINGPROFILE":"CJTKENNEDY",
// 			"USERDOMAIN":"CJTKENNEDY",
// 			"USERDNSDOMAIN":"CJTKENNEDY.COM",
// 			"TMP":"C:\\Users\\connor\\AppData\\Local\\Temp\\",
// 			"TERM":"msys",
// 			"TEMP":"C:\\Users\\connor\\AppData\\Local\\Temp\\",
// 			"SystemRoot":"C:\\Windows",
// 			"SystemDrive":"C:",
// 			"SSH_AUTH_SOCK":"/tmp/ssh-zWVv5FFUKvDv/agent.12184",
// 			"SSH_AGENT_PID":"12276",
// 			"SESSIONNAME":"Console",
// 			"REDISCLOUD_URL":"redis://rediscloud:J4mdu6a6dYShaddE@redis-18664.c8.us-east-1-3.ec2.cloud.redislabs.com:18664",
// 			"PUBLIC":"C:\\Users\\Public",
// 			"PSModulePath":"C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Users\\connor\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files (x86)\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
// 			"PSExecutionPolicyPreference":"Unrestricted",
// 			"ProgramW6432":"C:\\Program Files",
// 			"ProgramFiles(x86)":"C:\\Program Files (x86)",
// 			"ProgramFiles":"C:\\Program Files",
// 			"ProgramData":"C:\\ProgramData",
// 			"PROCESSOR_REVISION":"0200",
// 			"PROCESSOR_LEVEL":"21",
// 			"PROCESSOR_IDENTIFIER":"AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD",
// 			"PROCESSOR_ARCHITECTURE":"AMD64",
// 			"posh_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PoshGit_a2be688889e1b24632e83adccd9b2a44b91d655b\\profile.example.ps1",
// 			"PM2_PROGRAMMATIC":"true",
// 			"PM2_JSON_PROCESSING":"true",
// 			"PM2_INTERACTOR_PROCESSING":"true",
// 			"PLINK_PROTOCOL":"ssh",
// 			"PGSSLMODE":"require",
// 			"PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
// 			"Path":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\cmd;C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\usr\\bin;C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\usr\\share\\git-tfs;C:\\Users\\connor\\AppData\\Local\\Apps\\2.0\\X9Q91ADO.37Z\\Z0KKYXX8.73L\\gith..tion_317444273a93ac29_0003.0003_665ccbdbd3c2d8d4;C:\\Users\\connor\\AppData\\Local\\GitHub\\lfs-amd64_1.3.1;C:\\Python27\\;C:\\Python27\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git\\cmd;C:\\Windows\\system32\\config\\systemprofile\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Users\\connor\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\connor\\AppData\\Roaming\\npm;C:\\Program Files\\rclone;C:\\Program Files\\Heroku\\bin;C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v8.1A\\bin\\NETFX 4.5.1 Tools\\x64",
// 			"OS":"Windows_NT",
// 			"OneDrive":"C:\\Users\\connor\\OneDrive",
// 			"NUMBER_OF_PROCESSORS":"8",
// 			"NODE_ENV":"development",
// 			"MOZ_PLUGIN_PATH":"C:\\Program Files (x86)\\Foxit Software\\Foxit Reader\\plugins\\",
// 			"LOGONSERVER":"\\\\ADC",
// 			"LOCALAPPDATA":"C:\\Users\\connor\\AppData\\Local",
// 			"HOMEPATH":"\\Users\\connor",
// 			"HOMEDRIVE":"C:",
// 			"HOME":"C:\\Users\\connor",
// 			"git_install_root":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11",
// 			"github_shell":"true",
// 			"github_posh_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PoshGit_a2be688889e1b24632e83adccd9b2a44b91d655b",
// 			"github_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11",
// 			"EDITOR":"GitPad",
// 			"DATABASE_URL":"postgres://tzluogucwufjfr:4a65cb2ed4d7a1c8ca0df85f9ee5549aa33e50c176161e137e47fca2b3b7542d@ec2-54-235-92-236.compute-1.amazonaws.com:5432/d9m59b6dn4gol2",
// 			"ComSpec":"C:\\Windows\\system32\\cmd.exe",
// 			"COMPUTERNAME":"CONNORPC",
// 			"CommonProgramW6432":"C:\\Program Files\\Common Files",
// 			"CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files",
// 			"CommonProgramFiles":"C:\\Program Files\\Common Files",
// 			"asl.log":"Destination=file",
// 			"APPDATA":"C:\\Users\\connor\\AppData\\Roaming",
// 			"ALLUSERSPROFILE":"C:\\ProgramData",
// 			"status":"online",
// 			"pm_uptime":1483646657345,
// 			"axm_actions":[
//
// 			],
// 			"axm_monitor":{
// 				"Loop delay":{
// 					"alert":{
//
// 					},
// 					"agg_type":"avg",
// 					"value":"50ms"
// 				}
// 			},
// 			"axm_options":{
// 				"default_actions":true,
// 				"http":false,
// 				"http_latency":200,
// 				"http_code":500,
// 				"ignore_routes":[
//
// 				],
// 				"profiling":true,
// 				"errors":true,
// 				"alert_enabled":true,
// 				"custom_probes":true,
// 				"network":false,
// 				"ports":false,
// 				"module_conf":{
//
// 				},
// 				"module_name":"dkmerger",
// 				"module_version":"2.2.3",
// 				"pmx_version":"0.6.8",
// 				"error":true
// 			},
// 			"axm_dynamic":{
//
// 			},
// 			"created_at":1483646657345,
// 			"pm_id":1,
// 			"restart_time":0,
// 			"unstable_restarts":0,
// 			"_pm2_version":"2.2.3",
// 			"versioning":null,
// 			"node_version":"7.1.0"
// 		},
// 		"pm_id":1,
// 		"monit":{
// 			"memory":66424832,
// 			"cpu":262
// 		}
// 	},
// 	{
// 		"pid":10460,
// 		"name":"dkmerger",
// 		"pm2_env":{
// 			"exec_mode":"cluster_mode",
// 			"env":{
// 				"dkmerger":"{}",
// 				"PM2_HOME":"C:\\Users\\connor\\.pm2",
// 				"windir":"C:\\Windows",
// 				"VSSDK140Install":"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VSSDK\\",
// 				"VS140COMNTOOLS":"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\",
// 				"USERPROFILE":"C:\\Users\\connor",
// 				"USERNAME":"connor",
// 				"USERDOMAIN_ROAMINGPROFILE":"CJTKENNEDY",
// 				"USERDOMAIN":"CJTKENNEDY",
// 				"USERDNSDOMAIN":"CJTKENNEDY.COM",
// 				"TMP":"C:\\Users\\connor\\AppData\\Local\\Temp\\",
// 				"TERM":"msys",
// 				"TEMP":"C:\\Users\\connor\\AppData\\Local\\Temp\\",
// 				"SystemRoot":"C:\\Windows",
// 				"SystemDrive":"C:",
// 				"SSH_AUTH_SOCK":"/tmp/ssh-zWVv5FFUKvDv/agent.12184",
// 				"SSH_AGENT_PID":"12276",
// 				"SESSIONNAME":"Console",
// 				"REDISCLOUD_URL":"redis://rediscloud:J4mdu6a6dYShaddE@redis-18664.c8.us-east-1-3.ec2.cloud.redislabs.com:18664",
// 				"PUBLIC":"C:\\Users\\Public",
// 				"PSModulePath":"C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Users\\connor\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files (x86)\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
// 				"PSExecutionPolicyPreference":"Unrestricted",
// 				"ProgramW6432":"C:\\Program Files",
// 				"ProgramFiles(x86)":"C:\\Program Files (x86)",
// 				"ProgramFiles":"C:\\Program Files",
// 				"ProgramData":"C:\\ProgramData",
// 				"PROCESSOR_REVISION":"0200",
// 				"PROCESSOR_LEVEL":"21",
// 				"PROCESSOR_IDENTIFIER":"AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD",
// 				"PROCESSOR_ARCHITECTURE":"AMD64",
// 				"posh_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PoshGit_a2be688889e1b24632e83adccd9b2a44b91d655b\\profile.example.ps1",
// 				"PM2_PROGRAMMATIC":"true",
// 				"PM2_JSON_PROCESSING":"true",
// 				"PM2_INTERACTOR_PROCESSING":"true",
// 				"PLINK_PROTOCOL":"ssh",
// 				"PGSSLMODE":"require",
// 				"PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
// 				"Path":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\cmd;C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\usr\\bin;C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\usr\\share\\git-tfs;C:\\Users\\connor\\AppData\\Local\\Apps\\2.0\\X9Q91ADO.37Z\\Z0KKYXX8.73L\\gith..tion_317444273a93ac29_0003.0003_665ccbdbd3c2d8d4;C:\\Users\\connor\\AppData\\Local\\GitHub\\lfs-amd64_1.3.1;C:\\Python27\\;C:\\Python27\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git\\cmd;C:\\Windows\\system32\\config\\systemprofile\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Users\\connor\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\connor\\AppData\\Roaming\\npm;C:\\Program Files\\rclone;C:\\Program Files\\Heroku\\bin;C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v8.1A\\bin\\NETFX 4.5.1 Tools\\x64",
// 				"OS":"Windows_NT",
// 				"OneDrive":"C:\\Users\\connor\\OneDrive",
// 				"NUMBER_OF_PROCESSORS":"8",
// 				"NODE_ENV":"development",
// 				"MOZ_PLUGIN_PATH":"C:\\Program Files (x86)\\Foxit Software\\Foxit Reader\\plugins\\",
// 				"LOGONSERVER":"\\\\ADC",
// 				"LOCALAPPDATA":"C:\\Users\\connor\\AppData\\Local",
// 				"HOMEPATH":"\\Users\\connor",
// 				"HOMEDRIVE":"C:",
// 				"HOME":"C:\\Users\\connor",
// 				"git_install_root":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11",
// 				"github_shell":"true",
// 				"github_posh_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PoshGit_a2be688889e1b24632e83adccd9b2a44b91d655b",
// 				"github_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11",
// 				"EDITOR":"GitPad",
// 				"DATABASE_URL":"postgres://tzluogucwufjfr:4a65cb2ed4d7a1c8ca0df85f9ee5549aa33e50c176161e137e47fca2b3b7542d@ec2-54-235-92-236.compute-1.amazonaws.com:5432/d9m59b6dn4gol2",
// 				"ComSpec":"C:\\Windows\\system32\\cmd.exe",
// 				"COMPUTERNAME":"CONNORPC",
// 				"CommonProgramW6432":"C:\\Program Files\\Common Files",
// 				"CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files",
// 				"CommonProgramFiles":"C:\\Program Files\\Common Files",
// 				"asl.log":"Destination=file",
// 				"APPDATA":"C:\\Users\\connor\\AppData\\Roaming",
// 				"ALLUSERSPROFILE":"C:\\ProgramData"
// 			},
// 			"treekill":true,
// 			"autorestart":true,
// 			"automation":true,
// 			"pmx":true,
// 			"vizion":true,
// 			"instances":4,
// 			"max_memory_restart":536870912,
// 			"name":"dkmerger",
// 			"node_args":[
//
// 			],
// 			"pm_exec_path":"C:\\Users\\connor\\Documents\\GitHub\\wedding\\app.js",
// 			"pm_cwd":"C:\\Users\\connor\\Documents\\GitHub\\wedding",
// 			"exec_interpreter":"node",
// 			"pm_out_log_path":"C:\\Users\\connor\\.pm2\\logs\\dkmerger-out-2.log",
// 			"pm_err_log_path":"C:\\Users\\connor\\.pm2\\logs\\dkmerger-error-2.log",
// 			"pm_pid_path":"C:\\Users\\connor\\.pm2\\pids\\dkmerger-2.pid",
// 			"NODE_APP_INSTANCE":2,
// 			"vizion_running":false,
// 			"dkmerger":"{}",
// 			"PM2_HOME":"C:\\Users\\connor\\.pm2",
// 			"windir":"C:\\Windows",
// 			"VSSDK140Install":"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VSSDK\\",
// 			"VS140COMNTOOLS":"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\",
// 			"USERPROFILE":"C:\\Users\\connor",
// 			"USERNAME":"connor",
// 			"USERDOMAIN_ROAMINGPROFILE":"CJTKENNEDY",
// 			"USERDOMAIN":"CJTKENNEDY",
// 			"USERDNSDOMAIN":"CJTKENNEDY.COM",
// 			"TMP":"C:\\Users\\connor\\AppData\\Local\\Temp\\",
// 			"TERM":"msys",
// 			"TEMP":"C:\\Users\\connor\\AppData\\Local\\Temp\\",
// 			"SystemRoot":"C:\\Windows",
// 			"SystemDrive":"C:",
// 			"SSH_AUTH_SOCK":"/tmp/ssh-zWVv5FFUKvDv/agent.12184",
// 			"SSH_AGENT_PID":"12276",
// 			"SESSIONNAME":"Console",
// 			"REDISCLOUD_URL":"redis://rediscloud:J4mdu6a6dYShaddE@redis-18664.c8.us-east-1-3.ec2.cloud.redislabs.com:18664",
// 			"PUBLIC":"C:\\Users\\Public",
// 			"PSModulePath":"C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Users\\connor\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files (x86)\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
// 			"PSExecutionPolicyPreference":"Unrestricted",
// 			"ProgramW6432":"C:\\Program Files",
// 			"ProgramFiles(x86)":"C:\\Program Files (x86)",
// 			"ProgramFiles":"C:\\Program Files",
// 			"ProgramData":"C:\\ProgramData",
// 			"PROCESSOR_REVISION":"0200",
// 			"PROCESSOR_LEVEL":"21",
// 			"PROCESSOR_IDENTIFIER":"AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD",
// 			"PROCESSOR_ARCHITECTURE":"AMD64",
// 			"posh_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PoshGit_a2be688889e1b24632e83adccd9b2a44b91d655b\\profile.example.ps1",
// 			"PM2_PROGRAMMATIC":"true",
// 			"PM2_JSON_PROCESSING":"true",
// 			"PM2_INTERACTOR_PROCESSING":"true",
// 			"PLINK_PROTOCOL":"ssh",
// 			"PGSSLMODE":"require",
// 			"PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
// 			"Path":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\cmd;C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\usr\\bin;C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\usr\\share\\git-tfs;C:\\Users\\connor\\AppData\\Local\\Apps\\2.0\\X9Q91ADO.37Z\\Z0KKYXX8.73L\\gith..tion_317444273a93ac29_0003.0003_665ccbdbd3c2d8d4;C:\\Users\\connor\\AppData\\Local\\GitHub\\lfs-amd64_1.3.1;C:\\Python27\\;C:\\Python27\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git\\cmd;C:\\Windows\\system32\\config\\systemprofile\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Users\\connor\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\connor\\AppData\\Roaming\\npm;C:\\Program Files\\rclone;C:\\Program Files\\Heroku\\bin;C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v8.1A\\bin\\NETFX 4.5.1 Tools\\x64",
// 			"OS":"Windows_NT",
// 			"OneDrive":"C:\\Users\\connor\\OneDrive",
// 			"NUMBER_OF_PROCESSORS":"8",
// 			"NODE_ENV":"development",
// 			"MOZ_PLUGIN_PATH":"C:\\Program Files (x86)\\Foxit Software\\Foxit Reader\\plugins\\",
// 			"LOGONSERVER":"\\\\ADC",
// 			"LOCALAPPDATA":"C:\\Users\\connor\\AppData\\Local",
// 			"HOMEPATH":"\\Users\\connor",
// 			"HOMEDRIVE":"C:",
// 			"HOME":"C:\\Users\\connor",
// 			"git_install_root":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11",
// 			"github_shell":"true",
// 			"github_posh_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PoshGit_a2be688889e1b24632e83adccd9b2a44b91d655b",
// 			"github_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11",
// 			"EDITOR":"GitPad",
// 			"DATABASE_URL":"postgres://tzluogucwufjfr:4a65cb2ed4d7a1c8ca0df85f9ee5549aa33e50c176161e137e47fca2b3b7542d@ec2-54-235-92-236.compute-1.amazonaws.com:5432/d9m59b6dn4gol2",
// 			"ComSpec":"C:\\Windows\\system32\\cmd.exe",
// 			"COMPUTERNAME":"CONNORPC",
// 			"CommonProgramW6432":"C:\\Program Files\\Common Files",
// 			"CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files",
// 			"CommonProgramFiles":"C:\\Program Files\\Common Files",
// 			"asl.log":"Destination=file",
// 			"APPDATA":"C:\\Users\\connor\\AppData\\Roaming",
// 			"ALLUSERSPROFILE":"C:\\ProgramData",
// 			"status":"online",
// 			"pm_uptime":1483646658092,
// 			"axm_actions":[
//
// 			],
// 			"axm_monitor":{
// 				"Loop delay":{
// 					"alert":{
//
// 					},
// 					"agg_type":"avg",
// 					"value":"49.11ms"
// 				}
// 			},
// 			"axm_options":{
// 				"default_actions":true,
// 				"http":false,
// 				"http_latency":200,
// 				"http_code":500,
// 				"ignore_routes":[
//
// 				],
// 				"profiling":true,
// 				"errors":true,
// 				"alert_enabled":true,
// 				"custom_probes":true,
// 				"network":false,
// 				"ports":false,
// 				"module_conf":{
//
// 				},
// 				"module_name":"dkmerger",
// 				"module_version":"2.2.3",
// 				"pmx_version":"0.6.8",
// 				"error":true
// 			},
// 			"axm_dynamic":{
//
// 			},
// 			"created_at":1483646658092,
// 			"pm_id":2,
// 			"restart_time":0,
// 			"unstable_restarts":0,
// 			"_pm2_version":"2.2.3",
// 			"versioning":null,
// 			"node_version":"7.1.0"
// 		},
// 		"pm_id":2,
// 		"monit":{
// 			"memory":66621440,
// 			"cpu":262
// 		}
// 	},
// 	{
// 		"pid":11452,
// 		"name":"dkmerger",
// 		"pm2_env":{
// 			"exec_mode":"cluster_mode",
// 			"env":{
// 				"dkmerger":"{}",
// 				"PM2_HOME":"C:\\Users\\connor\\.pm2",
// 				"windir":"C:\\Windows",
// 				"VSSDK140Install":"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VSSDK\\",
// 				"VS140COMNTOOLS":"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\",
// 				"USERPROFILE":"C:\\Users\\connor",
// 				"USERNAME":"connor",
// 				"USERDOMAIN_ROAMINGPROFILE":"CJTKENNEDY",
// 				"USERDOMAIN":"CJTKENNEDY",
// 				"USERDNSDOMAIN":"CJTKENNEDY.COM",
// 				"TMP":"C:\\Users\\connor\\AppData\\Local\\Temp\\",
// 				"TERM":"msys",
// 				"TEMP":"C:\\Users\\connor\\AppData\\Local\\Temp\\",
// 				"SystemRoot":"C:\\Windows",
// 				"SystemDrive":"C:",
// 				"SSH_AUTH_SOCK":"/tmp/ssh-zWVv5FFUKvDv/agent.12184",
// 				"SSH_AGENT_PID":"12276",
// 				"SESSIONNAME":"Console",
// 				"REDISCLOUD_URL":"redis://rediscloud:J4mdu6a6dYShaddE@redis-18664.c8.us-east-1-3.ec2.cloud.redislabs.com:18664",
// 				"PUBLIC":"C:\\Users\\Public",
// 				"PSModulePath":"C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Users\\connor\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files (x86)\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
// 				"PSExecutionPolicyPreference":"Unrestricted",
// 				"ProgramW6432":"C:\\Program Files",
// 				"ProgramFiles(x86)":"C:\\Program Files (x86)",
// 				"ProgramFiles":"C:\\Program Files",
// 				"ProgramData":"C:\\ProgramData",
// 				"PROCESSOR_REVISION":"0200",
// 				"PROCESSOR_LEVEL":"21",
// 				"PROCESSOR_IDENTIFIER":"AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD",
// 				"PROCESSOR_ARCHITECTURE":"AMD64",
// 				"posh_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PoshGit_a2be688889e1b24632e83adccd9b2a44b91d655b\\profile.example.ps1",
// 				"PM2_PROGRAMMATIC":"true",
// 				"PM2_JSON_PROCESSING":"true",
// 				"PM2_INTERACTOR_PROCESSING":"true",
// 				"PLINK_PROTOCOL":"ssh",
// 				"PGSSLMODE":"require",
// 				"PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
// 				"Path":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\cmd;C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\usr\\bin;C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\usr\\share\\git-tfs;C:\\Users\\connor\\AppData\\Local\\Apps\\2.0\\X9Q91ADO.37Z\\Z0KKYXX8.73L\\gith..tion_317444273a93ac29_0003.0003_665ccbdbd3c2d8d4;C:\\Users\\connor\\AppData\\Local\\GitHub\\lfs-amd64_1.3.1;C:\\Python27\\;C:\\Python27\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git\\cmd;C:\\Windows\\system32\\config\\systemprofile\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Users\\connor\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\connor\\AppData\\Roaming\\npm;C:\\Program Files\\rclone;C:\\Program Files\\Heroku\\bin;C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v8.1A\\bin\\NETFX 4.5.1 Tools\\x64",
// 				"OS":"Windows_NT",
// 				"OneDrive":"C:\\Users\\connor\\OneDrive",
// 				"NUMBER_OF_PROCESSORS":"8",
// 				"NODE_ENV":"development",
// 				"MOZ_PLUGIN_PATH":"C:\\Program Files (x86)\\Foxit Software\\Foxit Reader\\plugins\\",
// 				"LOGONSERVER":"\\\\ADC",
// 				"LOCALAPPDATA":"C:\\Users\\connor\\AppData\\Local",
// 				"HOMEPATH":"\\Users\\connor",
// 				"HOMEDRIVE":"C:",
// 				"HOME":"C:\\Users\\connor",
// 				"git_install_root":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11",
// 				"github_shell":"true",
// 				"github_posh_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PoshGit_a2be688889e1b24632e83adccd9b2a44b91d655b",
// 				"github_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11",
// 				"EDITOR":"GitPad",
// 				"DATABASE_URL":"postgres://tzluogucwufjfr:4a65cb2ed4d7a1c8ca0df85f9ee5549aa33e50c176161e137e47fca2b3b7542d@ec2-54-235-92-236.compute-1.amazonaws.com:5432/d9m59b6dn4gol2",
// 				"ComSpec":"C:\\Windows\\system32\\cmd.exe",
// 				"COMPUTERNAME":"CONNORPC",
// 				"CommonProgramW6432":"C:\\Program Files\\Common Files",
// 				"CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files",
// 				"CommonProgramFiles":"C:\\Program Files\\Common Files",
// 				"asl.log":"Destination=file",
// 				"APPDATA":"C:\\Users\\connor\\AppData\\Roaming",
// 				"ALLUSERSPROFILE":"C:\\ProgramData"
// 			},
// 			"treekill":true,
// 			"autorestart":true,
// 			"automation":true,
// 			"pmx":true,
// 			"vizion":true,
// 			"instances":4,
// 			"max_memory_restart":536870912,
// 			"name":"dkmerger",
// 			"node_args":[
//
// 			],
// 			"pm_exec_path":"C:\\Users\\connor\\Documents\\GitHub\\wedding\\app.js",
// 			"pm_cwd":"C:\\Users\\connor\\Documents\\GitHub\\wedding",
// 			"exec_interpreter":"node",
// 			"pm_out_log_path":"C:\\Users\\connor\\.pm2\\logs\\dkmerger-out-3.log",
// 			"pm_err_log_path":"C:\\Users\\connor\\.pm2\\logs\\dkmerger-error-3.log",
// 			"pm_pid_path":"C:\\Users\\connor\\.pm2\\pids\\dkmerger-3.pid",
// 			"NODE_APP_INSTANCE":3,
// 			"vizion_running":false,
// 			"dkmerger":"{}",
// 			"PM2_HOME":"C:\\Users\\connor\\.pm2",
// 			"windir":"C:\\Windows",
// 			"VSSDK140Install":"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VSSDK\\",
// 			"VS140COMNTOOLS":"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\",
// 			"USERPROFILE":"C:\\Users\\connor",
// 			"USERNAME":"connor",
// 			"USERDOMAIN_ROAMINGPROFILE":"CJTKENNEDY",
// 			"USERDOMAIN":"CJTKENNEDY",
// 			"USERDNSDOMAIN":"CJTKENNEDY.COM",
// 			"TMP":"C:\\Users\\connor\\AppData\\Local\\Temp\\",
// 			"TERM":"msys",
// 			"TEMP":"C:\\Users\\connor\\AppData\\Local\\Temp\\",
// 			"SystemRoot":"C:\\Windows",
// 			"SystemDrive":"C:",
// 			"SSH_AUTH_SOCK":"/tmp/ssh-zWVv5FFUKvDv/agent.12184",
// 			"SSH_AGENT_PID":"12276",
// 			"SESSIONNAME":"Console",
// 			"REDISCLOUD_URL":"redis://rediscloud:J4mdu6a6dYShaddE@redis-18664.c8.us-east-1-3.ec2.cloud.redislabs.com:18664",
// 			"PUBLIC":"C:\\Users\\Public",
// 			"PSModulePath":"C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Users\\connor\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files (x86)\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
// 			"PSExecutionPolicyPreference":"Unrestricted",
// 			"ProgramW6432":"C:\\Program Files",
// 			"ProgramFiles(x86)":"C:\\Program Files (x86)",
// 			"ProgramFiles":"C:\\Program Files",
// 			"ProgramData":"C:\\ProgramData",
// 			"PROCESSOR_REVISION":"0200",
// 			"PROCESSOR_LEVEL":"21",
// 			"PROCESSOR_IDENTIFIER":"AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD",
// 			"PROCESSOR_ARCHITECTURE":"AMD64",
// 			"posh_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PoshGit_a2be688889e1b24632e83adccd9b2a44b91d655b\\profile.example.ps1",
// 			"PM2_PROGRAMMATIC":"true",
// 			"PM2_JSON_PROCESSING":"true",
// 			"PM2_INTERACTOR_PROCESSING":"true",
// 			"PLINK_PROTOCOL":"ssh",
// 			"PGSSLMODE":"require",
// 			"PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
// 			"Path":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\cmd;C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\usr\\bin;C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11\\usr\\share\\git-tfs;C:\\Users\\connor\\AppData\\Local\\Apps\\2.0\\X9Q91ADO.37Z\\Z0KKYXX8.73L\\gith..tion_317444273a93ac29_0003.0003_665ccbdbd3c2d8d4;C:\\Users\\connor\\AppData\\Local\\GitHub\\lfs-amd64_1.3.1;C:\\Python27\\;C:\\Python27\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\nodejs\\;C:\\Program Files\\Git\\cmd;C:\\Windows\\system32\\config\\systemprofile\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Users\\connor\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\connor\\AppData\\Roaming\\npm;C:\\Program Files\\rclone;C:\\Program Files\\Heroku\\bin;C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v8.1A\\bin\\NETFX 4.5.1 Tools\\x64",
// 			"OS":"Windows_NT",
// 			"OneDrive":"C:\\Users\\connor\\OneDrive",
// 			"NUMBER_OF_PROCESSORS":"8",
// 			"NODE_ENV":"development",
// 			"MOZ_PLUGIN_PATH":"C:\\Program Files (x86)\\Foxit Software\\Foxit Reader\\plugins\\",
// 			"LOGONSERVER":"\\\\ADC",
// 			"LOCALAPPDATA":"C:\\Users\\connor\\AppData\\Local",
// 			"HOMEPATH":"\\Users\\connor",
// 			"HOMEDRIVE":"C:",
// 			"HOME":"C:\\Users\\connor",
// 			"git_install_root":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11",
// 			"github_shell":"true",
// 			"github_posh_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PoshGit_a2be688889e1b24632e83adccd9b2a44b91d655b",
// 			"github_git":"C:\\Users\\connor\\AppData\\Local\\GitHub\\PortableGit_d7effa1a4a322478cd29c826b52a0c118ad3db11",
// 			"EDITOR":"GitPad",
// 			"DATABASE_URL":"postgres://tzluogucwufjfr:4a65cb2ed4d7a1c8ca0df85f9ee5549aa33e50c176161e137e47fca2b3b7542d@ec2-54-235-92-236.compute-1.amazonaws.com:5432/d9m59b6dn4gol2",
// 			"ComSpec":"C:\\Windows\\system32\\cmd.exe",
// 			"COMPUTERNAME":"CONNORPC",
// 			"CommonProgramW6432":"C:\\Program Files\\Common Files",
// 			"CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files",
// 			"CommonProgramFiles":"C:\\Program Files\\Common Files",
// 			"asl.log":"Destination=file",
// 			"APPDATA":"C:\\Users\\connor\\AppData\\Roaming",
// 			"ALLUSERSPROFILE":"C:\\ProgramData",
// 			"status":"online",
// 			"pm_uptime":1483646658859,
// 			"axm_actions":[
//
// 			],
// 			"axm_monitor":{
// 				"Loop delay":{
// 					"alert":{
//
// 					},
// 					"agg_type":"avg",
// 					"value":"41.99ms"
// 				}
// 			},
// 			"axm_options":{
// 				"default_actions":true,
// 				"http":false,
// 				"http_latency":200,
// 				"http_code":500,
// 				"ignore_routes":[
//
// 				],
// 				"profiling":true,
// 				"errors":true,
// 				"alert_enabled":true,
// 				"custom_probes":true,
// 				"network":false,
// 				"ports":false,
// 				"module_conf":{
//
// 				},
// 				"module_name":"dkmerger",
// 				"module_version":"2.2.3",
// 				"pmx_version":"0.6.8",
// 				"error":true
// 			},
// 			"axm_dynamic":{
//
// 			},
// 			"created_at":1483646658859,
// 			"pm_id":3,
// 			"restart_time":0,
// 			"unstable_restarts":0,
// 			"_pm2_version":"2.2.3",
// 			"versioning":null,
// 			"node_version":"7.1.0"
// 		},
// 		"pm_id":3,
// 		"monit":{
// 			"memory":66641920,
// 			"cpu":240
// 		}
// 	}
// ]
